charts/zitadel/Chart.yaml
charts/zitadel/templates/deployment.yaml

Pods are not recreated When `helm upgrade` is invoked. This PR should fix this by calculating the checksum of the configmap. If the configmap changes the checksum differs and the deployment is patched. Whenever the deployment is updated the pods get recreated.

Restart pods on helm upgrade

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/servicemonitor.yaml

The tlsConfig field for the ServiceMonitor object is a Map. Therefore we need to handle it as a map.

Fix broken serviceMonitor tlsConfig

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/deployment.yaml

Hello, team
With the config like this, my pods couldn't serve traffic and enter a crash loop due to failure of livenessProbe
```yaml
zitadel:
masterkey: MX#dqpSDAF%ge7i#rG&y8vH$fEc5s**7
configmapConfig:
TLS:
Enabled: false
ExternalSecure: true
ExternalDomain: zitadel.mydomain.io
ExternalPort: 443
Database:
cockroach:
User:
Mode: 'verify-full'
RootCert: "/.secrets/ca.crt"
Cert: "/.secrets/tls.crt"
Key: "/.secrets/tls.key"
Admin:
Mode: 'verify-full'
RootCert: "/.secrets/ca.crt"
Cert: "/.secrets/tls.crt"
Key: "/.secrets/tls.key"
DefaultInstance:
DefaultLanguage: en
Org:
Name: 'Internal Users'
Human:
Username: 'root'
Password: 'RootPassword1!'
secretConfig:
Database:
cockroach:
User:
Password: a-zitadel-db-user-password
Admin:
Password: a-zitadel-db-root-password
replicaCount: 2
cockroachdb: …
```

fix(deployment): fix probes for external domain

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/deployment.yaml
charts/zitadel/values.yaml

I would like to use existing secrets to configure the deployment (e.g.: Postgres parameters)
For example when using crunchydata pgo the provisioned database and user parameters are generated into a secret. With this change this can be referenced instead of copying the parameters to a new zitadel secret.

Add option to configure additional env variables

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/deployment.yaml
charts/zitadel/values.yaml

Make it possible to configure readinessProbe, livenessProbe and the startupProbe for the deployment. By default all 3 probes are enabled and only require the minimal configuration because it automatically sets accurate default values.
**Default values:**
```yaml
readinessProbe:
initialDelaySeconds: 60
periodSeconds: 5
failureThreshold: 3
livenessProbe:
initialDelaySeconds: 60
periodSeconds: 5
failureThreshold: 3
startupProbe:
periodSeconds: 10
failureThreshold: 30
```
The startupProbe allows the pods to live longer before the first liveness check happens at first startup to make sure migrations properly run through. The startup time, before the first liveness check happens, is calculated by `failureThreshold * periodSeconds` and therefore by default waits 300s (5 minutes) before the first …

feat: allow configuring readinessProbe, livenessProbe and add a startupProbe

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/_helpers.tpl
charts/zitadel/templates/setupjob.yaml
charts/zitadel/values.yaml

- Makes the setup job key writer image repo and tag configurable. Defaults to the Helm Capabilities objects k8s version for the tag.
- Makes the outcommented FirstInstance config a bit clearer. 
- Removes a helper template that's used just once.

fix: configurable key writer image

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/deployment.yaml
charts/zitadel/templates/initjob.yaml
charts/zitadel/templates/secret_zitadel-masterkey.yaml
charts/zitadel/templates/setupjob.yaml

closes #57 
The check if an init container is needed just has to be done for the init job. The setup job and the deployment always mount at least the masterkey secret.

fix: enable empty secrets

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/secret_zitadel-secrets.yaml

fix: Only create secret if configuration is provided via `secretConfig`

---

README.md

The current URL does not link to the docs; removing the /docs/ path fixes the URL.

docs: fix URL for Zitadel k8s deployment guide

---

.github/workflows/test.yml
charts/zitadel/Chart.yaml
charts/zitadel/templates/NOTES.txt
charts/zitadel/templates/_helpers.tpl
charts/zitadel/templates/rbac.yaml
charts/zitadel/templates/setupjob.yaml

Templates in go 1.17 evaluated each argument to and/or, like for example:
```
{{- if and .Values.zitadel.configmapConfig.FirstInstance .Values.zitadel.configmapConfig.FirstInstance.Org .Values.zitadel.configmapConfig.FirstInstance.Org.Machine }}
```
This leads to nil pointers.
This PR adds
- a function to reliably check if a value is defined.
- a test in the pipeline that is executed with helm 3.9, which is compiled with go 1.17
The branch protection rule is already updated.

feat: support helm 3.9

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/initjob.yaml
charts/zitadel/values.yaml

This makes the initJob's backoffLimit configurable, so that it will restart as much as needed while waiting for mounted database TLS secrets to become available. This helps when databases are slower to provision than zitadel expects if you're deploying both at the same time.

Make the initJob's backoff limit configurable via values.yaml

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/_helpers.tpl

The Chart now uses `.Values.image.tag` for the Kubernetes label `app.kubernetes.io/version`. If `.Values.image.tag` is not set it defaults to `.Chart.AppVersion`.
Fixes #139

fix: Use `.Values.image.tag` for common labels

---

.github/workflows/test.yml

Since Kubernetes version 1.28 was released in August and is available for production use on various cloud providers, the chart should be tested against this version.

chore: Test against Kubernetes 1.28

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/initjob.yaml
charts/zitadel/values.yaml

Hello,
This little PR add an `initJob.command` option to allow users specify witch command want on init job.
This is really useful when we don't want specify "admin" DB user and not running init step manually.

feat: allow choose init command

---

examples/3-cockroach-insecure/README.md

Do not use the "--wait" option because the init is done by a post-install hook and without the init done the PODs will not start, so you would find yourself locked inside an infinite loop (db pods not working because of missing init and init job not starting because of db pods not working)

docs: cockroach helm install without wait

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/configmap.yaml
charts/zitadel/templates/deployment.yaml
charts/zitadel/values.yaml

Added the following annotation fields to support further customizability when using tooling that allows customization via annotations. #159
Stakater reloader & ArgoCD are examples of this, by allowing us to add annotations to these resources we can further control certain aspects of our environment.
This change is a pure addition to the code base and should not have any impact while upgrading.

feat: add annotation fields to configMap and deployment resources

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/configmap.yaml
charts/zitadel/templates/rbac.yaml
charts/zitadel/templates/secret_db-ssl-root-crt.yaml
charts/zitadel/templates/secret_zitadel-masterkey.yaml
charts/zitadel/templates/secret_zitadel-secrets.yaml
charts/zitadel/templates/serviceaccount.yaml
charts/zitadel/values.yaml

All information is referenced in https://github.com/zitadel/zitadel-charts/issues/161
As I would like to already incrementally fix this setup and ensure that Zitadel can easily be deployed the current proposal is to move these annotations:
```
helm.sh/hook: pre-install,pre-upgrade
helm.sh/hook-delete-policy: before-hook-creation
helm.sh/hook-weight: "1"
```
.. to the `values.yaml` as was basically already done for some resources already like the `initJob` [values.yaml#134](https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/values.yaml#L134)
Goal for the initial PR is to make a non-breaking change on the chart

feat: support multi-chart deployment

---

charts/zitadel/Chart.yaml

Update the `appVersion` so users of this Helm chart can just update to the latest version, and deploy `v2.49.1` of Zitadel.
Anything else need to be bumped with this?

feat: update appVersion to v2.49.1, current latest release

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/deployment.yaml
charts/zitadel/templates/initjob.yaml
charts/zitadel/templates/setupjob.yaml
charts/zitadel/values.yaml

feat: support extraVolumes and extraVolumeMounts

---

charts/zitadel/acceptance/accessibility.go

after v2.54.0 
`POST http://127.0.0.1.sslip.io:8080/oauth/v2/token` return Error.User.NotFound instead of assertion invalid
#210

test: add new error handling for user not found

---

README.md
charts/zitadel/Chart.yaml
charts/zitadel/acceptance/config.go

The default ZITADEL version is now v2.55.0.
[This requires Cockroach DB to be at >= v23.2](https://zitadel.com/docs/support/advisory/a10009)
If you are using an older version of Cockroach DB, please upgrade it before upgrading ZITADEL.
Note that in order to upgrade cockroach, you should not jump minor versions.
For example:
```bash
helm upgrade db cockroachdb/cockroachdb --version 11.2.4 --reuse-values
helm upgrade db cockroachdb/cockroachdb --version 12.0.5 --reuse-values
helm upgrade db cockroachdb/cockroachdb --version 13.0.1 --reuse-values
helm upgrade my-zitadel zitadel/zitadel --version 8.0.0 --reuse-values
```
Please refer to the docs by Cockroach Labs. The ZITADEL tests run against the [official CockroachDB chart](https://artifacthub.io/packages/helm/cockroachdb/cockroachdb). …

feat: upgrade default app version to v2.55.0

---

.github/workflows/bump.yml

Invoke this workflow manually when you want to create an updated Helm chart. If you pass in a ZITADEL release tag, then that is the version the new chart will use, otherwise the chart will automatically refer to the latest version.
[Related chat thread](https://discord.com/channels/927474939156643850/1226884380262137937)

chore: fix bump workflow for manual runs

---

.github/workflows/bump.yml

With this my hope is the workflow started in #235 is now functional.

chore: helm chart bump.yml repair

---

.github/dependabot.yml

With this change, Dependabot will automatically be creating pull-requests for any shared actions or workflows used in Github Workflows.  
This means deprecations such as [this](https://github.com/zitadel/zitadel-charts/actions/runs/10008104661) will be a thing of the past fairly soon:
> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Hope you can use it!

chore: Dependabot updates for used Github Actions

---

.github/workflows/bump.yml

Checks for PRs created automatically using the GITHUB_TOKEN secret are pending forever. This prevents merging these PRs.
PRs created using a GitHub App token can trigger other workflows needed for their checks.

chore: run checks on auto PRs

---

.github/workflows/bump.yml

According to the action docs, sort-tags is disabled by default if releases-only is true.
https://github.com/oprypin/find-latest-tag?tab=readme-ov-file#inputs
Which is why the bump action can get wrong zitadel versions, like here: https://github.com/zitadel/zitadel-charts/pull/247
We explicitly enable sort-tags to fix this.

chore: sort tags

---

.github/workflows/bump.yml

GitHub workflows don't react on push events created with the GITHUB_TOKEN secret in order to avoid circular runs.
To bypass this, we have to create the events with the GitHub App token.
This ensures that the workflow .github/workflows/release.yml is triggered on auto PR merges.

chore: trigger releases from auto PRs

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/deployment.yaml

When TLS is enabled it produces a duplicate `scheme` for probes: one for HTTP and the other one for HTTPS
```yaml
TLS:
Enabled: true
KeyPath: /tls/tls.key
CertPath: /tls/tls.crt
```

fix: duplicate scheme in probes when TLS is enabled

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/debug_replicaset.yaml
charts/zitadel/templates/deployment.yaml
charts/zitadel/templates/initjob.yaml
charts/zitadel/templates/setupjob.yaml
charts/zitadel/values.yaml

Being able to configure Zitadel using environment variables just like it is mentioned [here](https://zitadel.com/docs/self-hosting/manage/configure#configure-by-environment-variables).
This is particularly useful when using external secrets operator for instance, we could retrieve the database/user credentials from there without having to put them into the Helm variables.
This is an alternative to defining each environment variable specifically in the Helm values too.
My work in progress: https://github.com/Smana/cloud-native-ref/pull/448

feat: sourcing envVars from a secret

---

.github/workflows/test.yml
go.mod

Uses go v1.23 to run the testsuite.
Even though this code is not meant to be imported and therefore this change is IMO not necessary according to https://github.com/zitadel/zitadel/issues/8906 because it already uses a supported go version, it can't hurt to upgrade it anyway.

test: use go 1.23

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/service.yaml
charts/zitadel/values.yaml

The appProtocol and the named ports for probes are very different things. The PR that added this together was didn't consider the valid values for appProtocol and how these aren't valid names for ports.
As per the Kubernetes documentation, the appProtocol:
```
kubectl explain svc.spec.ports.appProtocol
KIND:       Service
VERSION:    v1
FIELD: appProtocol <string>
DESCRIPTION:
The application protocol for this port. This is used as a hint for
implementations to offer richer behavior for protocols that they understand.
This field follows standard Kubernetes label syntax. Valid values are
either:
* Un-prefixed protocol names - reserved for IANA standard service names (as
per RFC-6335 and https://www.iana.org/assignments/service-names).
* Kubernetes-defined prefixed names:
* …
```

fix(appProtocol): ensure appProtocol can be valid without invalidating probes

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/debug_replicaset.yaml
charts/zitadel/templates/deployment.yaml
charts/zitadel/templates/initjob.yaml
charts/zitadel/templates/setupjob.yaml
charts/zitadel/values.yaml

This piggybacks off #287 and extends the functionality to initContainers. This is an essential enhancement if you want to use a [native Kubernetes Sidecar](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/) instead of an extra container. This allows Jobs to function as expected rather than hanging forever. The primary use case is deploying to Google's CloudSQL and allowing the init/setup jobs to work and exit properly.

feat: Add ability to specify initContainers

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/setupjob.yaml
charts/zitadel/values.yaml

With this PR, we make the setup jobs backoff limit configurable like we did it for the init job already.
Closes #314

feat(setup): make backoffLimit configurable

---

.github/workflows/bump.yml

The [wrong trigger was removed](https://github.com/zitadel/zitadel-charts/pull/325/files) recently.
I thought leaving repository_dispatch would make sure the pipelines in Zitadel keep succeeding.
[It turns out they need workflow_dispatch, not repository_dispatch](https://github.com/zitadel/zitadel/actions/runs/14132072401/job/39596105609).
This PR reverts the triggers to the state they were when everything worked.

chore: add workflow dispatch again

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/_helpers.tpl
charts/zitadel/templates/debug_replicaset.yaml
charts/zitadel/templates/deployment.yaml
charts/zitadel/templates/initjob.yaml
charts/zitadel/templates/pdb.yaml
charts/zitadel/templates/servicemonitor.yaml
charts/zitadel/templates/setupjob.yaml

The deployment was missing a component label, so that its pods could be differentiated from those of the other components (init and setup jobs). This led the pod disruption budget to match pods of the other components, making draining of nodes (for example during a rolling replace of a node group) fail.

fix: correct labels and selector labels

---

README.md
charts/zitadel/Chart.yaml

We released Zitadel v4.
We are not aware of any issues relating to the charts v9-rc2 release.
Therefore, we remove the pre-release status from the Chart, too.

feat: use Zitadel v4

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/deployment_login.yaml
charts/zitadel/values.yaml

This change introduces `login.env` and `login.envVarsSecret` in values.yaml and wires them into the login Deployment template. Users can now provide static environment variables or reference a Kubernetes Secret in the same way the main zitadel deployment supports them. The default `NEXT_PUBLIC_BASE_PATH=/ui/v2/login` is still included, and any additional variables defined under `login.env` will be appended. This keeps the login deployment consistent with the existing zitadel setup while enabling customization of runtime environment.

feat(login): add support for environment variables in login deployment

---

charts/zitadel/Chart.yaml
charts/zitadel/templates/debug_replicaset.yaml

The debug ReplicaSet template still referenced templates/configmap.yaml, which was renamed in 9.x. This caused Helm template failures when zitadel.debug.enabled=true. The checksum annotation has been updated to allow the debug pod to be deployed again.
Closes #369

fix: update reference to renamed configmap.yaml in debug_replicaset

---

.github/workflows/typecheck.yml
Makefile
README.md

This PR adds Helm chart validation using kubeconform to catch manifest issues early in the CI pipeline. The validation runs via `make check`, which renders the Helm templates and validates them against Kubernetes API schemas without requiring a cluster. This helps ensure chart changes produce valid Kubernetes resources before they're tested or deployed.

chore: add kubeconform validation for Helm charts
